#parameters of the model
model_selection:
  model:
    XGBClassifier:
      search_param_grid:
        max_depth: [5, 7]
        n_estimators: [100, 150]
        learning_rate: [0.01, 0.1, 0.3]

    GradientBoostingClassifier:
      search_param_grid:
        n_estimators: [100, 200]
        learning_rate: [0.05, 0.1]
        max_depth: [3, 5]
        criterion: ["friedman_mse"]

    RandomForestClassifier:
      search_param_grid:
        n_estimators: [100, 200]
        max_depth: [5, 10]
        min_samples_split: [2]
        criterion: ["gini", "entropy"]


# model_selection:
#   model:
#     XGBClassifier:
#       search_param_grid:
#         max_depth:
#           - 5
#           - 7
#         n_estimators:
#           - 10
#           - 20
#     GradientBoostingClassifier:
#       search_param_grid:
#         n_estimators:
#           - 100
#         criterion:
#           -friedman_mse
      
#     RandomForestClassifier:
#       search_param_grid:
#         n_estimators:
#           - 100
#           - 200
#         max_depth:
#           - 5
#           - 10
#         min_samples_split:
#           - 2
#         min_samples_split:
#           - 1


